export default [

  {
    id: 1,
    nombre: "Machu Picchu",
    pais: "Perú",
    descripcion: "Antigua ciudad inca situada en los Andes peruanos.",
    imagen: "https://fotografias-2.larazon.es/clipping/cmsimages01/2020/05/30/5A9F9423-35D0-4D02-85F4-CE8ED35C1691/97.jpg?crop=6000,3375,x0,y313&width=1600&height=900&optimize=low&format=webply",
    rating: 5.0,
    precioCOP: 850000,
    tipoActividad: "aventura",
    categoria: "histórico",
    clima: "frío",
    presupuesto: "alto",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "mayo - octubre",
    actividades: ["caminatas", "fotografía", "ruinas"]
  },

  {
    id: 2,
    nombre: "Torre Eiffel",
    pais: "Francia",
    descripcion: "El monumento más icónico de París.",
    imagen: "https://res.cloudinary.com/dtljonz0f/image/upload/f_auto/q_auto/v1/gc-v1/paris/3%20giorni%20a%20Parigi%20Tour%20Eiffel?_a=BAVAZGGf0",
    rating: 4.9,
    precioCOP: 120000,
    tipoActividad: "urbano",
    categoria: "arquitectura",
    clima: "templado",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "abril - junio",
    actividades: ["miradores", "fotografía"]
  },

  {
    id: 3,
    nombre: "Muralla China",
    pais: "China",
    descripcion: "Una de las construcciones más impresionantes del mundo.",
    imagen: "https://media.istockphoto.com/id/2151863095/es/foto/the-great-wall-of-china.jpg?s=612x612&w=0&k=20&c=1iJ45-yQlKHqnyYmr6BDOCW9A4jTQuyCb4YoVHq_gq4=",
    rating: 5.0,
    precioCOP: 1400000,
    tipoActividad: "aventura",
    categoria: "maravilla",
    clima: "variable",
    presupuesto: "alto",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "septiembre - noviembre",
    actividades: ["caminatas", "historia"]
  },

  {
    id: 4,
    nombre: "Taj Mahal",
    pais: "India",
    descripcion: "Mausoleo de mármol considerado un símbolo de amor.",
    imagen: "https://static.nationalgeographicla.com/files/styles/image_3200/public/93080.jpg?w=1900&h=1425",
    rating: 4.9,
    precioCOP: 1300000,
    tipoActividad: "relajación",
    categoria: "arquitectura",
    clima: "cálido",
    presupuesto: "alto",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "noviembre - marzo",
    actividades: ["fotografía", "tour guiado"]
  },

  {
    id: 5,
    nombre: "Estatua de la Libertad",
    pais: "Estados Unidos",
    descripcion: "Monumento americano ubicado en Nueva York.",
    imagen: "https://content-viajes.nationalgeographic.com.es/medio/2024/10/02/estatua-de-la-libertad_fbf37672_241002130423_1280x960.jpg",
    rating: 4.8,
    precioCOP: 600000,
    tipoActividad: "urbano",
    categoria: "atracción",
    clima: "variable",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "abril - octubre",
    actividades: ["miradores", "barco"]
  },

  {
    id: 6,
    nombre: "Cristo Redentor",
    pais: "Brasil",
    descripcion: "Icónica estatua ubicada en Río de Janeiro.",
    imagen: "https://fotografias.lasexta.com/clipping/cmsimages02/2015/12/08/364CF973-35F7-43E8-8E20-2561BA6039BD/default.jpg?crop=1300,731,x0,y52&width=1900&height=1069&optimize=low&format=webply",
    rating: 4.8,
    precioCOP: 450000,
    tipoActividad: "urbano",
    categoria: "religioso",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "junio - septiembre",
    actividades: ["miradores", "fotografía"]
  },

  {
    id: 7,
    nombre: "Puerta de Brandeburgo",
    pais: "Alemania",
    descripcion: "Símbolo histórico ubicado en Berlín.",
    imagen: "https://dam.ngenespanol.com/wp-content/uploads/2021/10/E51XD8.jpg",
    rating: 4.7,
    precioCOP: 200000,
    tipoActividad: "urbano",
    categoria: "histórico",
    clima: "frío",
    presupuesto: "bajo",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "abril - octubre",
    actividades: ["fotografía", "paseos"]
  },

  {
    id: 8,
    nombre: "Coliseo Romano",
    pais: "Italia",
    descripcion: "Anfiteatro icónico de la antigua Roma.",
    imagen: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/SGGVVGEKYZHOFANSOINDHUFDDU.JPG",
    rating: 5.0,
    precioCOP: 900000,
    tipoActividad: "cultural",
    categoria: "histórico",
    clima: "templado",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "marzo - mayo",
    actividades: ["tour guiado", "historia"]
  },

  {
    id: 9,
    nombre: "Cataratas del Niágara",
    pais: "Estados Unidos / Canadá",
    descripcion: "Conjunto de cascadas imponentes en América del Norte.",
    imagen: "https://cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/M2LVFI562RJHSMZPS5K3QY6LBA.png",
    rating: 5.0,
    precioCOP: 700000,
    tipoActividad: "naturaleza",
    categoria: "parque",
    clima: "frío",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "mayo - octubre",
    actividades: ["barco", "miradores"]
  },

  {
    id: 10,
    nombre: "Torre de Pisa",
    pais: "Italia",
    descripcion: "Famosa torre inclinada ubicada en Pisa.",
    imagen: "https://i.blogs.es/cccea2/imagen_6/1366_2000.jpeg",
    rating: 4.6,
    precioCOP: 400000,
    tipoActividad: "cultural",
    categoria: "arquitectura",
    clima: "templado",
    presupuesto: "bajo",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "abril - septiembre",
    actividades: ["fotografía", "tour guiado"]
  },

  {
    id: 11,
    nombre: "Times Square",
    pais: "Estados Unidos",
    descripcion: "Zona icónica de Nueva York conocida por sus luces.",
    imagen: "https://www.gotokyo.org/es/see-and-do/tokyo-day-trip/sightseeing-guide/images/07.jpg",
    rating: 4.5,
    precioCOP: 500000,
    tipoActividad: "urbano",
    categoria: "ciudad",
    clima: "variable",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "abril - diciembre",
    actividades: ["compras", "fotografía", "caminatas"]
  },

  {
    id: 12,
    nombre: "Acropolis de Atenas",
    pais: "Grecia",
    descripcion: "Antigua ciudadela emblemática de Atenas.",
    imagen: "https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/DUCNW44SXZAHVGQTRBJNLTL6J4.jpg",
    rating: 4.9,
    precioCOP: 1100000,
    tipoActividad: "cultural",
    categoria: "histórico",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "baja",
    mejorEpoca: "abril - junio",
    actividades: ["historia", "ruinas"]
  },

  {
    id: 13,
    nombre: "Mont Saint-Michel",
    pais: "Francia",
    descripcion: "Isla rocosa con una abadía histórica.",
    imagen: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Mont_St_Michel_3%2C_Brittany_%28France%29_-_July_2011.jpg",
    rating: 4.8,
    precioCOP: 900000,
    tipoActividad: "aventura",
    categoria: "histórico",
    clima: "frío",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "mayo - septiembre",
    actividades: ["caminatas", "fotografía"]
  },

  {
    id: 14,
    nombre: "Cataratas Iguazú",
    pais: "Brasil / Argentina",
    descripcion: "Complejo de cascadas impresionante.",
    imagen: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/AYQ35SN77VHJXKFYXMQK7NEHZI.jpg",
    rating: 4.9,
    precioCOP: 800000,
    tipoActividad: "naturaleza",
    categoria: "parque",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "marzo - mayo",
    actividades: ["senderismo", "miradores"]
  },

  {
    id: 15,
    nombre: "Angkor Wat",
    pais: "Camboya",
    descripcion: "Complejo de templos budistas impresionante.",
    imagen: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Angkor_Wat_temple.jpg",
    rating: 5.0,
    precioCOP: 1600000,
    tipoActividad: "cultural",
    categoria: "religioso",
    clima: "cálido",
    presupuesto: "alto",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "noviembre - febrero",
    actividades: ["templos", "fotografía"]
  },

  {
    id: 16,
    nombre: "Gran Pirámide de Giza",
    pais: "Egipto",
    descripcion: "La mayor pirámide del Antiguo Egipto.",
    imagen: "https://media.traveler.es/photos/63cfb27dbf5aa5b9eef49f42/4:3/w_2132,h_1599,c_limit/GettyImages-572791893.jpg",
    rating: 5.0,
    precioCOP: 1500000,
    tipoActividad: "aventura",
    categoria: "histórico",
    clima: "cálido",
    presupuesto: "alto",
    tiempoVisita: "medio",
    accesibilidad: "baja",
    mejorEpoca: "octubre - abril",
    actividades: ["desierto", "historia"]
  },

  {
    id: 17,
    nombre: "Monte Fuji",
    pais: "Japón",
    descripcion: "Volcán icónico y símbolo japonés.",
    imagen: "https://travel.home.sndimg.com/content/dam/images/travel/stock/2016/12/1/GettyImages-691714409_mount-fuji.jpg.rend.hgtvcom.1280.960.suffix/1491588014967.jpeg",
    rating: 4.9,
    precioCOP: 1300000,
    tipoActividad: "aventura",
    categoria: "montaña",
    clima: "frío",
    presupuesto: "alto",
    tiempoVisita: "largo",
    accesibilidad: "media",
    mejorEpoca: "julio - septiembre",
    actividades: ["montañismo", "fotografía"]
  },

  {
    id: 18,
    nombre: "Parque Yosemite",
    pais: "Estados Unidos",
    descripcion: "Famoso parque natural con montañas y cascadas.",
    imagen: "https://images.ctfassets.net/u4vv676b8z52/4An9gj5GgB5PXE6ZOFqnA4/1b5ada6f99f7d3c47779fba399a097e7/yosemite-national-park-el-capitan.jpg",
    rating: 4.8,
    precioCOP: 900000,
    tipoActividad: "naturaleza",
    categoria: "parque",
    clima: "frío",
    presupuesto: "medio",
    tiempoVisita: "largo",
    accesibilidad: "media",
    mejorEpoca: "mayo - octubre",
    actividades: ["senderismo", "camping"]
  },

  {
    id: 19,
    nombre: "Sagrada Familia",
    pais: "España",
    descripcion: "Templo icónico diseñado por Gaudí.",
    imagen: "https://www.salason.es/wp-content/uploads/2024/04/Sagrada-Familia-Barcelona.jpg",
    rating: 4.8,
    precioCOP: 700000,
    tipoActividad: "cultural",
    categoria: "arquitectura",
    clima: "templado",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "abril - octubre",
    actividades: ["arquitectura", "fotografía"]
  },

  {
    id: 20,
    nombre: "Santorini",
    pais: "Grecia",
    descripcion: "Isla famosa por sus casas blancas y cúpulas azules.",
    imagen: "https://blog.gowalking.com.ar/wp-content/uploads/2016/06/casa-blanca-con-cupula-de-techos-azules-en-oia-santorini-grecia.jpg",
    rating: 4.9,
    precioCOP: 2000000,
    tipoActividad: "relajación",
    categoria: "playa",
    clima: "cálido",
    presupuesto: "alto",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "mayo - septiembre",
    actividades: ["playa", "fotografía", "caminatas"]
  },



  {
  id: 21,
  nombre: "Cerro de Monserrate",
  pais: "Colombia",
  descripcion: "Santuario ubicado en Bogotá con vistas panorámicas.",
  imagen: "https://radionacional-v3.s3.amazonaws.com/s3fs-public/styles/portadas_relaciona_4_3/public/node/article/field_image/MONSERRATE.jpg?h=efd05f9e&itok=TV3iPsvO",
  rating: 4.8,
  precioCOP: 25000,
  tipoActividad: "moderada",
  categoria: "montaña",
  clima: "frío",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "enero - marzo",
  actividades: ["caminatas", "fotografía", "miradores"]
},

{
  id: 22,
  nombre: "Villa de Leyva",
  pais: "Colombia",
  descripcion: "Pueblo colonial histórico de Colombia.",
  imagen: "https://mediaim.expedia.com/destination/1/aea1a89ec1f2cf2742d6b30fc85eb88b.jpg?impolicy=fcrop&w=450&h=280&q=medium",
  rating: 4.7,
  precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "histórico",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "alta",
  mejorEpoca: "julio - diciembre",
  actividades: ["cultura", "fotografía", "gastronomía"]
},

{
  id: 23,
  nombre: "Cartagena",
  pais: "Colombia",
  descripcion: "Ciudad amurallada con historia y encanto.",
  imagen: "https://media.staticontent.com/media/pictures/9495889e-54f9-40d2-939d-b04bf30b47c7",
  rating: 4.9,
  precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "ciudad",
  clima: "cálido",
  presupuesto: "alto",
  tiempoVisita: "largo",
  accesibilidad: "alta",
  mejorEpoca: "diciembre - abril",
  actividades: ["playa", "nocturna", "historia"]
},

{
  id: 24,
  nombre: "San Andrés",
  pais: "Colombia",
  descripcion: "Isla del mar de siete colores.",
  imagen: "https://www.fontur.com.co/sites/default/files/2024-06/c58425b4-e596-417b-b1a9-4c2e17023ad7.jpeg",
  rating: 4.8,
  precioCOP: 200000,
  tipoActividad: "relajación",
  categoria: "playa",
  clima: "tropical",
  presupuesto: "alto",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "junio - septiembre",
  actividades: ["snorkel", "playa", "paseos en bote"]
},

{
  id: 25,
  nombre: "Tayrona",
  pais: "Colombia",
  descripcion: "Parque natural con playas vírgenes y selva tropical.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfTjihs5rOmsmRv8PH0ZzqlULNfKpDie0Z2g&s",
  rating: 4.9,
  precioCOP: 50000,
  tipoActividad: "aventura",
  categoria: "parque natural",
  clima: "tropical",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "baja",
  mejorEpoca: "enero - marzo",
  actividades: ["senderismo", "playa", "naturaleza"]
},

{
  id: 26,
  nombre: "Caño Cristales",
  pais: "Colombia",
  descripcion: "El río de los cinco colores.",
  imagen: "https://miviajeporcolombia.com/wp-content/uploads/2023/01/-32-800x533.jpg.webp",
  rating: 5.0,
  precioCOP: 400000,
  tipoActividad: "aventura",
  categoria: "parque natural",
  clima: "cálido",
  presupuesto: "alto",
  tiempoVisita: "medio",
  accesibilidad: "baja",
  mejorEpoca: "junio - noviembre",
  actividades: ["senderismo", "fotografía", "naturaleza"]
},

{
  id: 27,
  nombre: "El Peñol de Guatapé",
  pais: "Colombia",
  descripcion: "Enorme roca con vista panorámica de embalses.",
  imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/8e/0a/63/colombia-and-experience.jpg?w=900&h=500&s=1",
  rating: 4.9,
  precioCOP: 30000,
  tipoActividad: "intensa",
  categoria: "montaña",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "marzo - junio",
  actividades: ["subida", "miradores", "fotografía"]
},

{
  id: 28,
  nombre: "Chicamocha",
  pais: "Colombia",
  descripcion: "Cañón impresionante con actividades de aventura.",
  imagen: "https://chicamochacanyonrace.com/wp-content/uploads/2025/04/1ec8bc82324accdbd314389dcb113cbd.webp",
  rating: 4.8,
  precioCOP: 60000,
  tipoActividad: "extrema",
  categoria: "montaña",
  clima: "cálido",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "agosto - octubre",
  actividades: ["parapente", "senderismo", "miradores"]
},

{
  id: 29,
  nombre: "Medellín Comuna 13",
  pais: "Colombia",
  descripcion: "Zona transformada conocida por sus murales.",
  imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/6c/a5/ef/ven-y-dejate-contar-la.jpg?w=900&h=500&s=1",
  rating: 4.7,
  precioCOP: 15000,
  tipoActividad: "cultural",
  categoria: "ciudad",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["arte urbano", "fotografía", "recorridos guiados"]
},

{
  id: 30,
  nombre: "Barichara",
  pais: "Colombia",
  descripcion: "Pueblo patrimonio considerado el más bonito de Colombia.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF73-HbgOgFUgcLr5jRA0wqICmo7HA1-s3PQ&s",
  rating: 4.9,
  precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "histórico",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "julio - noviembre",
  actividades: ["caminatas", "cultura", "fotografía"]
},

{
  id: 31,
  nombre: "Catedral de Sal de Zipaquirá",
  pais: "Colombia",
  descripcion: "Iglesia subterránea excavada en una mina de sal.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiMxHr5Gq1-5hoc7XKT7XSklEIwXWdZj95yg&s",
  rating: 4.8,
  precioCOP: 32000,
  tipoActividad: "cultural",
  categoria: "histórico",
  clima: "frío",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["recorridos", "fotografía", "cultura"]
},

{
  id: 32,
  nombre: "Nevado del Ruiz",
  pais: "Colombia",
  descripcion: "Volcán nevado con paisajes espectaculares.",
  imagen: "https://rutasdelosandes.com/images/rutas/caldas/nevado-del-ruiz/featured.jpg",
  rating: 4.7,
  precioCOP: 80000,
  tipoActividad: "intensa",
  categoria: "montaña",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "baja",
  mejorEpoca: "diciembre - febrero",
  actividades: ["senderismo", "fotografía", "montañismo"]
},

{
  id: 33,
  nombre: "Laguna de Tota",
  pais: "Colombia",
  descripcion: "La laguna de agua dulce más grande de Colombia.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROUCZgnWlMF0_f7X_yaRGRubdh-D62nYwYhQ&s",
  rating: 4.6,
  precioCOP: 40000,
  tipoActividad: "relajación",
  categoria: "playa",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "abril - agosto",
  actividades: ["caminatas", "kayak", "fotografía"]
},

{
  id: 34,
  nombre: "Desierto de la Tatacoa",
  pais: "Colombia",
  descripcion: "Paisaje desértico único ideal para astroturismo.",
  imagen: "https://www.otbcali.com/wp-content/uploads/2019/10/huila3.png",
  rating: 4.7,
  precioCOP: 50000,
  tipoActividad: "aventura",
  categoria: "desierto",
  clima: "seco",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "junio - septiembre",
  actividades: ["estrellas", "senderismo", "fotografía"]
},

{
  id: 35,
  nombre: "Parque del Café",
  pais: "Colombia",
  descripcion: "Parque temático del Eje Cafetero.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ__dJ-Q1hEPf_rsZf9GMMN1CIXZMrWnKLcdw&s",
  rating: 4.8,
  precioCOP: 85000,
  tipoActividad: "aventura",
  categoria: "parque temático",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["atracciones", "cultura", "fotografía"]
},

{
  id: 36,
  nombre: "Leticia Amazonas",
  pais: "Colombia",
  descripcion: "Puerta al Amazonas colombiano.",
  imagen: "https://periodico.unal.edu.co/uploads/2025/agosto/PeriodicoUNAL-100825-1-am.jpg",
  rating: 4.7,
  precioCOP: 300000,
  tipoActividad: "aventura",
  categoria: "selva",
  clima: "tropical",
  presupuesto: "alto",
  tiempoVisita: "largo",
  accesibilidad: "baja",
  mejorEpoca: "julio - octubre",
  actividades: ["avistamiento", "recorridos", "naturaleza"]
},

{
  id: 37,
  nombre: "Salitre Mágico",
  pais: "Colombia",
  descripcion: "Parque de diversiones en Bogotá.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP5vrltYOEK85yARmMp-QBZKU3yME8GyPZYQ&s",
  rating: 4.6,
  precioCOP: 65000,
  tipoActividad: "diversión",
  categoria: "parque temático",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "enero - abril",
  actividades: ["atracciones", "juegos", "familia"]
},

{
  id: 38,
  nombre: "Girón",
  pais: "Colombia",
  descripcion: "Pueblo colonial con arquitectura bien conservada.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR16v_nG4zDbp4MMVKoT_SkKhNKAYo_ME0ggA&s",
  rating: 4.6,
  precioCOP: 10000,
  tipoActividad: "relajación",
  categoria: "histórico",
  clima: "cálido",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "marzo - julio",
  actividades: ["caminatas", "cultura", "fotografía"]
},

{
  id: 39,
  nombre: "Popayán",
  pais: "Colombia",
  descripcion: "Ciudad blanca famosa por su gastronomía.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKP6hymDd6UospjeKDMWSgern0nc97SwoJpw&s",
  rating: 4.7,
  precioCOP: 35000,
  tipoActividad: "cultural",
  categoria: "ciudad",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "medio",
  accesibilidad: "alta",
  mejorEpoca: "septiembre - diciembre",
  actividades: ["gastronomía", "cultura", "fotografía"]
},

{
  id: 40,
  nombre: "Cali",
  pais: "Colombia",
  descripcion: "Capital mundial de la salsa.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAHqniHeHsVmFeSQ_PR1Wl0Hf36l5Ik49coQ&s",
  rating: 4.6,
  precioCOP: 45000,
  tipoActividad: "diversión",
  categoria: "ciudad",
  clima: "cálido",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "alta",
  mejorEpoca: "junio - septiembre",
  actividades: ["baile", "fiesta", "cultura"]
},

 // =============================
//  LUGARES 41 - 60 COMPLETOS
// =============================

  {
    id: 41,
    nombre: "Bucaramanga",
    pais: "Colombia",
    descripcion: "Ciudad con clima agradable y parques naturales.",
    imagen: "https://www.upb.edu.co/es/imagenes/img-sobrelaciudadbucaramanga-cam-1464102319822.jpg",
    rating: 4.6,
    precioCOP: 40000,
    tipoActividad: "urbanismo",
    categoria: "ciudad",
    clima: "templado",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "todo el año",
    actividades: ["parques", "caminatas", "gastronomía"]
  },
  {
    id: 42,
    nombre: "Santa Marta",
    pais: "Colombia",
    descripcion: "Ciudad costera cercana a la Sierra Nevada.",
    imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Rodadero_2023.jpg/330px-Rodadero_2023.jpg",
    rating: 4.6,
    precioCOP: 0,
    tipoActividad: "relajación",
    categoria: "playa",
    clima: "cálido",
    presupuesto: "económico",
    tiempoVisita: "medio",
    accesibilidad: "alta",
    mejorEpoca: "diciembre - abril",
    actividades: ["playa", "gastronomía", "tours"]
  },
  {
    id: 43,
    nombre: "Palomino",
    pais: "Colombia",
    descripcion: "Destino playero tranquilo en la costa caribeña.",
    imagen: "https://www.laguajira.gov.co/Prensa/SaladePrensa/PublishingImages/Palomino%2C%20La%20Guajira.jpg",
    rating: 4.7,
    precioCOP: 60000,
    tipoActividad: "relajación",
    categoria: "playa",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "enero - junio",
    actividades: ["tubing", "playa", "senderismo"]
  },
  {
    id: 44,
    nombre: "Cabo de la Vela",
    pais: "Colombia",
    descripcion: "Destino desértico en La Guajira con playas vírgenes.",
    imagen: "https://www.tomplanmytrip.com/wp-content/uploads/2024/07/Playa-Dorada-Cabo-de-la-vela-La-Guajira-Desert-Colombia-Eastern-Caribbean-Coast-.jpg",
    rating: 4.7,
    precioCOP: 100000,
    tipoActividad: "aventura",
    categoria: "desierto",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "baja",
    mejorEpoca: "agosto - noviembre",
    actividades: ["windsurf", "fotografía", "playa"]
  },
  {
    id: 45,
    nombre: "Islas del Rosario",
    pais: "Colombia",
    descripcion: "Archipiélago paradisíaco cerca de Cartagena.",
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e9/fb/58/caption.jpg?w=1000&h=1000&s=1",
    rating: 4.9,
    precioCOP: 250000,
    tipoActividad: "relajación",
    categoria: "playa",
    clima: "cálido",
    presupuesto: "alto",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "enero - abril",
    actividades: ["snorkel", "playa", "paseos en bote"]
  },
  {
    id: 46,
    nombre: "Cocora Valle",
    pais: "Colombia",
    descripcion: "Valle con las palmeras de cera más altas del mundo.",
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/4a/e8/a0/20190709-093333-largejpg.jpg?w=900&h=-1&s=1",
    rating: 4.8,
    precioCOP: 55000,
    tipoActividad: "aventura",
    categoria: "montaña",
    clima: "frío",
    presupuesto: "medio",
    tiempoVisita: "largo",
    accesibilidad: "media",
    mejorEpoca: "junio - septiembre",
    actividades: ["senderismo", "fotografía", "cabalgata"]
  },
  {
    id: 47,
    nombre: "San Gil",
    pais: "Colombia",
    descripcion: "Capital del turismo extremo.",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHGhATN9IQl-02nvrE6QsVpRc-GN6-yiZczA&s",
    rating: 4.8,
    precioCOP: 70000,
    tipoActividad: "adrenalina",
    categoria: "ciudad",
    clima: "templado",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "alta",
    mejorEpoca: "todo el año",
    actividades: ["rafting", "parapente", "cascadas"]
  },
  {
    id: 48,
    nombre: "Laguna de Guatavita",
    pais: "Colombia",
    descripcion: "Laguna sagrada relacionada con la leyenda del Dorado.",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPgz6M-xycmvRuFCbRYBJ0lFxvAymmp3dkKA&s",
    rating: 4.6,
    precioCOP: 20000,
    tipoActividad: "naturaleza",
    categoria: "laguna",
    clima: "frío",
    presupuesto: "económico",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "mayo - octubre",
    actividades: ["senderismo", "fotografía", "historia"]
  },
  {
    id: 49,
    nombre: "Playa Blanca",
    pais: "Colombia",
    descripcion: "Playas de arena blanca en Cartagena.",
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/75/2d/6c/playa-blanca.jpg?w=900&h=-1&s=1",
    rating: 4.7,
    precioCOP: 120000,
    tipoActividad: "relajación",
    categoria: "playa",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "enero - mayo",
    actividades: ["playa", "snorkel", "gastronomía"]
  },
  {
    id: 50,
    nombre: "Pereira",
    pais: "Colombia",
    descripcion: "Ciudad del Eje Cafetero con atracciones turísticas.",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM0xY_sRX2V1qPAVZtYgFZLNXIFCSqCu8FQA&s",
    rating: 4.6,
    precioCOP: 0,
    tipoActividad: "urbanismo",
    categoria: "ciudad",
    clima: "templado",
    presupuesto: "económico",
    tiempoVisita: "medio",
    accesibilidad: "alta",
    mejorEpoca: "todo el año",
    actividades: ["gastronomía", "cultura", "cafeteros"]
  },
  {
    id: 51,
    nombre: "Manizales",
    pais: "Colombia",
    descripcion: "Ciudad cafetera con clima frío y paisajes.",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKWBp46SzsQIInQqRWWTi3fOhq52FF-4qe6g&s",
    rating: 4.6,
    precioCOP: 0,
    tipoActividad: "urbanismo",
    categoria: "ciudad",
    clima: "frío",
    presupuesto: "económico",
    tiempoVisita: "medio",
    accesibilidad: "alta",
    mejorEpoca: "julio - noviembre",
    actividades: ["miradores", "cultura", "cafetero"]
  },
  {
    id: 52,
    nombre: "Armenia",
    pais: "Colombia",
    descripcion: "Ciudad rodeada de cafetales en el Eje Cafetero.",
    imagen: "https://cdn.georgia.to/img/thumbnails/AqosZKhT4E5VuTcPTR5PLF_smedium.jpg",
    rating: 4.6,
    precioCOP: 0,
    tipoActividad: "urbanismo",
    categoria: "ciudad",
    clima: "templado",
    presupuesto: "económico",
    tiempoVisita: "medio",
    accesibilidad: "alta",
    mejorEpoca: "todo el año",
    actividades: ["cafetero", "cultura", "caminatas"]
  },
  {
    id: 53,
    nombre: "Ibagué",
    pais: "Colombia",
    descripcion: "Concierto de flores y música conservatorio.",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv_s1kN07V4zsfgRFYs19SRKPzeYoDbBWyng&s",
    rating: 4.5,
    precioCOP: 25000,
    tipoActividad: "urbanismo",
    categoria: "ciudad",
    clima: "templado",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "abril - noviembre",
    actividades: ["música", "cultura", "parques"]
  },
  {
    id: 54,
    nombre: "Villavicencio",
    pais: "Colombia",
    descripcion: "Puerta a los Llanos Orientales.",
    imagen: "https://viajaporcolombia.com/images/cinco-lugares-para-conocer-en-villavicencio.jpg",
    rating: 4.5,
    precioCOP: 15000,
    tipoActividad: "naturaleza",
    categoria: "llanos",
    clima: "cálido",
    presupuesto: "económico",
    tiempoVisita: "medio",
    accesibilidad: "alta",
    mejorEpoca: "enero - marzo",
    actividades: ["cabalgata", "cultura llanera", "senderos"]
  },
  {
    id: 55,
    nombre: "Pasto",
    pais: "Colombia",
    descripcion: "Ciudad con gran patrimonio cultural y gastronómico.",
    imagen: "https://miviajeporcolombia.com/wp-content/uploads/2025/03/que-hacer-en-pasto-lo-que-no-te-debes-perder-800x600.jpg.webp",
    rating: 4.6,
    precioCOP: 30000,
    tipoActividad: "cultura",
    categoria: "ciudad",
    clima: "frío",
    presupuesto: "económico",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "enero (carnaval)",
    actividades: ["cultura", "gastronomía", "festivales"]
  },
  {
    id: 56,
    nombre: "Tunja",
    pais: "Colombia",
    descripcion: "Capital histórica de Boyacá con arquitectura colonial.",
    imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Vista_al_centro_hist%C3%B3rica_en_un_d%C3%ADa_nublado_en_la_Plaza_de_Bol%C3%ADvar_en_Tunja.jpg/250px-Vista_al_centro_hist%C3%B3rica_en_un_d%C3%ADa_nublado_en_la_Plaza_de_Bol%C3%ADvar_en_Tunja.jpg",
    rating: 4.5,
    precioCOP: 10000,
    tipoActividad: "cultura",
    categoria: "ciudad",
    clima: "frío",
    presupuesto: "económico",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "agosto - octubre",
    actividades: ["historia", "arquitectura", "museos"]
  },
  {
    id: 57,
    nombre: "Honda",
    pais: "Colombia",
    descripcion: "Pueblo histórico sobre el río Magdalena.",
    imagen: "https://colombia.travel/sites/default/files/styles/imagen_650x450_escala_y_recorte/public/destino/42_Honda_CVV3829_Retocada%20%281%29%20%281%29%20%281%29.jpg?itok=Qy-4aUS3",
    rating: 4.5,
    precioCOP: 0,
    tipoActividad: "historia",
    categoria: "pueblo",
    clima: "cálido",
    presupuesto: "económico",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "junio - septiembre",
    actividades: ["historia", "caminatas", "río"]
  },
  {
    id: 58,
    nombre: "Melgar",
    pais: "Colombia",
    descripcion: "Destino de aguas termales y balnearios.",
    imagen: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Panoramica_Centro_Melgar.jpg",
    rating: 4.6,
    precioCOP: 50000,
    tipoActividad: "relajación",
    categoria: "balneario",
    clima: "cálido",
    presupuesto: "medio",
    tiempoVisita: "corto",
    accesibilidad: "alta",
    mejorEpoca: "febrero - abril",
    actividades: ["piscinas", "termales", "parques acuáticos"]
  },
  {
    id: 59,
    nombre: "Choachí",
    pais: "Colombia",
    descripcion: "Pueblo con vista a la Sabana de Bogotá.",
    imagen: "https://content.r9cdn.net/rimg/dimg/26/19/ccb5e198-city-94454-17345fad3ec.jpg?width=1366&height=768&xhint=1742&yhint=1831&crop=true",
    rating: 4.5,
    precioCOP: 5000,
    tipoActividad: "naturaleza",
    categoria: "montaña",
    clima: "frío",
    presupuesto: "económico",
    tiempoVisita: "corto",
    accesibilidad: "media",
    mejorEpoca: "abril - agosto",
    actividades: ["senderismo", "miradores", "cascadas"]
  },
  {
    id: 60,
    nombre: "Suesca",
    pais: "Colombia",
    descripcion: "Destino para escalada en roca y actividades naturales.",
    imagen: "https://hotelcaminodelasal.com/wp-content/uploads/2021/11/attractive_364.jpg",
    rating: 4.6,
    precioCOP: 20000,
    tipoActividad: "aventura",
    categoria: "montaña",
    clima: "frío",
    presupuesto: "económico",
    tiempoVisita: "medio",
    accesibilidad: "media",
    mejorEpoca: "enero - marzo",
    actividades: ["escalada", "senderismo", "camping"]
  },


{ 
  id: 61, nombre: "Jardín", pais: "Colombia",
  descripcion: "Pueblo antioqueño colorido y acogedor.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKE_1FEr5TNmFnS6iVPtW61YCWJVet2aKbhQ&s",
  rating: 4.8, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "pueblo",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "enero - abril",
  actividades: ["caminatas", "fotografía", "cafetería"]
},

{
  id: 62, nombre: "Guatapé", pais: "Colombia",
  descripcion: "Pueblo colorido con casas de múltiples colores.",
  imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/b9/ed/93/piedra-del-penol.jpg?w=1200&h=700&s=1",
  rating: 4.8, precioCOP: 0,
  tipoActividad: "aventura",
  categoria: "pueblo",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "alta",
  mejorEpoca: "junio - octubre",
  actividades: ["escalada", "kayak", "fotografía"]
},

{
  id: 63, nombre: "Jericó", pais: "Colombia",
  descripcion: "Pueblo cafetero con paisajes hermosos.",
  imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/a4/8d/0a/cerro-las-nubes.jpg?w=1200&h=700&s=1",
  rating: 4.7, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "montaña",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "julio - noviembre",
  actividades: ["senderismo", "cafetería", "miradores"]
},

{
  id: 64, nombre: "La Ceja", pais: "Colombia",
  descripcion: "Municipio del Valle de Aburrá con comercio activo.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB-cFAjL0x6VK81QJUMgxBBSlS_C36RyBZsQ&s",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "urbano",
  categoria: "ciudad",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["compras", "cafés", "parques"]
},

{
  id: 65, nombre: "Rionegro", pais: "Colombia",
  descripcion: "Municipio antioqueño con centro comercial.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9ClWEiZCr9edtwbY18sBhjkDa6eN4pVznGQ&s",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "urbano",
  categoria: "ciudad",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["compras", "restaurantes"]
},

{
  id: 66, nombre: "Envigado", pais: "Colombia",
  descripcion: "Municipio del Valle de Aburrá cercano a Medellín.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9hBVjfJF3bkOt2kFEdBPpw_P-15ukSb1P6g&s",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "urbano",
  categoria: "ciudad",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["gastronomía", "bares", "caminatas urbanas"]
},

{
  id: 67, nombre: "Sabaneta", pais: "Colombia",
  descripcion: "Municipio residencial del área metropolitana.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg-40_uJ_PqC8LcvWIwLX78lqmLPvcGjxCjQ&s",
  rating: 4.4, precioCOP: 0,
  tipoActividad: "urbano",
  categoria: "ciudad",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["restaurantes", "cultura", "plaza"]
},

{
  id: 68, nombre: "Itagüí", pais: "Colombia",
  descripcion: "Municipio industrial del Valle de Aburrá.",
  imagen: "https://itagui.gov.co/uploads/noticias/8b85b-image002-7-.jpg",
  rating: 4.4, precioCOP: 0,
  tipoActividad: "urbano",
  categoria: "ciudad",
  clima: "caluroso",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["compras", "cultura"]
},

{
  id: 69, nombre: "La Estrella", pais: "Colombia",
  descripcion: "Municipio del Valle de Aburrá con naturaleza.",
  imagen: "https://2024.laestrella.gov.co/kcfinder/upload/images/foto-ganadora-concurso-fotografia-2016.png",
  rating: 4.4, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "montaña",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "febrero - julio",
  actividades: ["senderismo", "miradores"]
},

{
  id: 70, nombre: "Copacabana", pais: "Colombia",
  descripcion: "Municipio del Valle de Aburrá con atracciones naturales.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTklSBtsXv-9ae2klRS-7-hh66O5ljL4F99xA&s",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "aventura",
  categoria: "montaña",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "junio - septiembre",
  actividades: ["senderismo", "escalada"]
},

{
  id: 71, nombre: "Belmira", pais: "Colombia",
  descripcion: "Pueblo cafetero serrano de Antioquia.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH_rnAlGFiKyP3Ivjo7bG4-QsxSZRVJY5VBQ&s",
  rating: 4.6, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "pueblo",
  clima: "frío",
  presupuesto: "bajo",
  tiempoVisita: "medio",
  accesibilidad: "baja",
  mejorEpoca: "octubre - diciembre",
  actividades: ["caminatas", "fotografía"]
},

{
  id: 72, nombre: "Abejorral", pais: "Colombia",
  descripcion: "Municipio antioqueño con paisaje de montaña.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpuMyR95M159gNb8b2aIsz6BYuhv4qJnF4jA&s",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "aventura",
  categoria: "montaña",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "enero - mayo",
  actividades: ["senderismo", "ciclismo"]
},

{
  id: 73, nombre: "Sonsón", pais: "Colombia",
  descripcion: "Pueblo histórico del oriente antioqueño.",
  imagen: "https://sonson-antioquia.gov.co/SiteAssets/SonsonTw/assets/img/bg-micrositios-interes.jpg",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "cultural",
  categoria: "pueblo",
  clima: "frío",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "marzo - julio",
  actividades: ["museos", "iglesias", "fotografía"]
},

{
  id: 74, nombre: "Retiro", pais: "Colombia",
  descripcion: "Municipio cafetero del oriente cercano.",
  imagen: "https://www.civitatis.com/f/espana/madrid/guia/el-retiro.jpg",
  rating: 4.4, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "pueblo",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "todo el año",
  actividades: ["parques", "senderismo"]
},

{
  id: 75, nombre: "San Vicente", pais: "Colombia",
  descripcion: "Municipio del Oriente Cercano de Antioquia.",
  imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/4d/43/96/st-vincent-and-the-grenadines.jpg?w=1200&h=700&s=1",
  rating: 4.4, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "pueblo",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "mayo - octubre",
  actividades: ["miradores", "fotografía"]
},

{
  id: 76, nombre: "Guarne", pais: "Colombia",
  descripcion: "Municipio del Oriente Cercano con flores.",
  imagen: "https://upload.wikimedia.org/wikipedia/commons/6/65/Guarne_Visionm.ph.jpg",
  rating: 4.5, precioCOP: 0,
  tipoActividad: "cultural",
  categoria: "pueblo",
  clima: "frío",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "junio - septiembre",
  actividades: ["floricultura", "parques"]
},

{
  id: 77, nombre: "Marinilla", pais: "Colombia",
  descripcion: "Municipio con patrimonio arquitectónico.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDwE_OBpeCEq-7nGjWco0QdK2J3wiD9IGPcw&s",
  rating: 4.6, precioCOP: 0,
  tipoActividad: "cultural",
  categoria: "pueblo",
  clima: "templado",
  presupuesto: "medio",
  tiempoVisita: "corto",
  accesibilidad: "alta",
  mejorEpoca: "julio - diciembre",
  actividades: ["arquitectura", "iglesias"]
},

{
  id: 78, nombre: "El Carmen de Viboral", pais: "Colombia",
  descripcion: "Pueblo con cerámica tradicional.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbLv3Bm4ussW3L_BI0-NZ-Z42uHq1VPU6IgA&s",
  rating: 4.6, precioCOP: 0,
  tipoActividad: "cultural",
  categoria: "pueblo",
  clima: "templado",
  presupuesto: "bajo",
  tiempoVisita: "medio",
  accesibilidad: "alta",
  mejorEpoca: "abril - agosto",
  actividades: ["cerámica", "talleres", "cafeterías"]
},

{
  id: 79, nombre: "Cogua", pais: "Colombia",
  descripcion: "Municipio cerca de Bogotá con vistas panorámicas.",
  imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/43/cc/1c/getlstd-property-photo.jpg?w=1200&h=1200&s=1",
  rating: 4.5, precioCOP: 10000,
  tipoActividad: "aventura",
  categoria: "montaña",
  clima: "frío",
  presupuesto: "medio",
  tiempoVisita: "medio",
  accesibilidad: "media",
  mejorEpoca: "enero - mayo",
  actividades: ["senderismo", "miradores"]
},

{
  id: 80, nombre: "Zipacón", pais: "Colombia",
  descripcion: "Municipio de Cundinamarca con naturaleza.",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg1UwXpibb9eSepC-94uucxOrCeVxc_XEJtg&s",
  rating: 4.4, precioCOP: 0,
  tipoActividad: "relajación",
  categoria: "montaña",
  clima: "frío",
  presupuesto: "bajo",
  tiempoVisita: "corto",
  accesibilidad: "media",
  mejorEpoca: "abril - julio",
  actividades: ["senderismo", "fotografía"]
},

  { id: 81, nombre: "Fusagasugá", pais: "Colombia", descripcion: "Ciudad valle con clima tropical.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe_HajyuM0_x5qhuppV5AXaWZB6wXqLdHfEw&s", rating: 4.6, precioCOP: 35000 },
  { id: 82, nombre: "Silvania", pais: "Colombia", descripcion: "Municipio con cascadas y naturaleza.", imagen: "https://www.silvania-cundinamarca.gov.co/MiMunicipio/PublishingImages/Paginas/Sitios-de-Interes/silvania%20tierra%20de%20promision.jpg", rating: 4.6, precioCOP: 25000 },
  { id: 83, nombre: "Tibacuy", pais: "Colombia", descripcion: "Municipio con cascadas y piscinas naturales.", imagen: "https://i.ytimg.com/vi/fGOBDn4w0M4/maxresdefault.jpg", rating: 4.7, precioCOP: 30000 },
  { id: 84, nombre: "Granada", pais: "España", descripcion: "Ciudad con La Alhambra y patrimonio moro.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/bltfe84b60fcde838af/68061cda696c05ff4835e25c/BCC-2024-EXPLORER-GRANADA-WINTER_GUIDE-HEADER-MOBILE.jpg?format=webp&quality=60&width=1440", rating: 4.9, precioCOP: 3200000 },
  { id: 85, nombre: "Sevilla", pais: "España", descripcion: "Ciudad histórica con la Giralda y flamenco.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt5b8acbfd396a737b/67b326bd0607f9cc254c2796/iStock-2028221960-HEADER_MOBILE.jpg?fit=crop&disable=upscale&auto=webp&quality=60&crop=smart", rating: 4.9, precioCOP: 3500000 },
  { id: 86, nombre: "Barcelona", pais: "España", descripcion: "Ciudad con arquitectura de Gaudí y playas.", imagen: "https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-barcelona-1.jpg", rating: 4.9, precioCOP: 3800000 },
  { id: 87, nombre: "Madrid", pais: "España", descripcion: "Capital con museos, gastronomía y vida nocturna.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwlKE6eS9GcNUQPkNpM7hlKrx53wM6lMsqOQ&s", rating: 4.8, precioCOP: 3600000 },
  { id: 88, nombre: "Valencia", pais: "España", descripcion: "Ciudad futurista con la Ciudad de las Artes.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5XRYj2cf8sroLK3sn8ucfc8KUcvQkr0r18w&s", rating: 4.8, precioCOP: 3400000 },
  { id: 89, nombre: "Córdoba", pais: "España", descripcion: "Ciudad histórica con la Mezquita-Catedral.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Centro_Hist%C3%B3rico%2C_16.9_--_2023_--_C%C3%B3rdoba%2C_Espa%C3%B1a.jpg/330px-Centro_Hist%C3%B3rico%2C_16.9_--_2023_--_C%C3%B3rdoba%2C_Espa%C3%B1a.jpg", rating: 4.8, precioCOP: 3200000 },
  { id: 90, nombre: "Toledo", pais: "España", descripcion: "Ciudad medieval amurallada con vistas espectaculares.", imagen: "https://whc.unesco.org/uploads/thumbs/site_0379_0038-400-400-20231002171105.webp", rating: 4.9, precioCOP: 3100000 },
  { id: 91, nombre: "Lisboa", pais: "Portugal", descripcion: "Capital con colinas, azulejos y tejo.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Lisbon_%2836831596786%29_%28cropped%29.jpg/330px-Lisbon_%2836831596786%29_%28cropped%29.jpg", rating: 4.8, precioCOP: 2800000 },
  { id: 92, nombre: "Porto", pais: "Portugal", descripcion: "Ciudad de vino y patrimonio histórico.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXWInHtogvLsc0OoAojooI7jqf89l8ei9--Q&s", rating: 4.8, precioCOP: 2700000 },
  { id: 93, nombre: "Sintra", pais: "Portugal", descripcion: "Pueblos montañosos con palacios románticos.", imagen: "https://media.traveler.es/photos/613763ba70e3cff8b85f8196/master/w_1600%2Cc_limit/190271.jpg", rating: 4.8, precioCOP: 2600000 },
  { id: 94, nombre: "París", pais: "Francia", descripcion: "La ciudad de la luz con arte y romance.", imagen: "https://cdn2.civitatis.com/francia/paris/galeria/torre-eiffel-altura.jpg", rating: 5.0, precioCOP: 4200000 },
  { id: 95, nombre: "Niza", pais: "Francia", descripcion: "Costa azul con playas y paseo marítimo.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh5PLv2bkBFkNNB5clvIq1NPg3_AZ7sEua6w&s", rating: 4.9, precioCOP: 3900000 },
  { id: 96, nombre: "Marsella", pais: "Francia", descripcion: "Puerto histórico en el Mediterráneo.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRksopffQ0muzp8OGdjv0P6YtiGEACULb5qIw&s", rating: 4.7, precioCOP: 3700000 },
  { id: 97, nombre: "Lyon", pais: "Francia", descripcion: "Ciudad de gastronomía y museo.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdTJR2DRDDoqsRR6b6kfy7FTSfm2BMTyCCAw&s", rating: 4.7, precioCOP: 3600000 },
  { id: 98, nombre: "Versalles", pais: "Francia", descripcion: "Palacio histórico con jardines impresionantes.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7rOJByL46rtUBePWvdkyafTGvozqxtmVZzQ&s", rating: 4.9, precioCOP: 3800000 },
  { id: 99, nombre: "Ámsterdam", pais: "Países Bajos", descripcion: "Ciudad de canales y bicicletas.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLGimB9Z6izJdGi379sbfdf5DT_F5Qgj3kXw&s", rating: 4.9, precioCOP: 3500000 },
  { id: 100, nombre: "Róterdam", pais: "Países Bajos", descripcion: "Puerto moderno con arquitectura futurista.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/e7/69/5e/rotterdam.jpg?w=700&h=400&s=1", rating: 4.7, precioCOP: 3400000 },
  { id: 101, nombre: "Londres", pais: "Reino Unido", descripcion: "Capital con museos, Big Ben y Thames.", imagen: "https://content.r9cdn.net/rimg/dimg/8a/d8/29dcb2f0-city-28501-17579c53c1d.jpg?width=1366&height=768&xhint=1560&yhint=1280&crop=true", rating: 4.9, precioCOP: 4000000 },
  { id: 102, nombre: "Oxford", pais: "Reino Unido", descripcion: "Ciudad universitaria histórica.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/4d/43/c1/oxford.jpg?w=1200&h=700&s=1", rating: 4.8, precioCOP: 3700000 },
  { id: 103, nombre: "Cambridge", pais: "Reino Unido", descripcion: "Ciudad de universidad con arquitectura medieval.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRncAjJ1xndNDkJ9dTxU-BpkuOUrvU9wFftcQ&s", rating: 4.8, precioCOP: 3700000 },
  { id: 104, nombre: "Edimburgo", pais: "Escocia", descripcion: "Ciudad histórica con castillo y Festival.", imagen: "https://www.visitscotland.com/binaries/content/gallery/visitscotland/cms-images/2022/06/30/301/calton-hill-evening", rating: 4.9, precioCOP: 3800000 },
  { id: 105, nombre: "Dublín", pais: "Irlanda", descripcion: "Capital con literatura, cerveza y tradición.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Dublin_-_aerial_-_panorama_-_2025-02-06.jpg/1200px-Dublin_-_aerial_-_panorama_-_2025-02-06.jpg", rating: 4.8, precioCOP: 3600000 },
  { id: 106, nombre: "Cork", pais: "Irlanda", descripcion: "Segunda ciudad con vida cultural activa.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt901dOU1J1ilUlEznD7jC3O9eymJXa_zcfw&s", rating: 4.7, precioCOP: 3500000 },
  { id: 107, nombre: "Berlín", pais: "Alemania", descripcion: "Capital con historia, arte y vida nocturna.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Museumsinsel_Berlin_Juli_2021_1_%28cropped%29_b.jpg/330px-Museumsinsel_Berlin_Juli_2021_1_%28cropped%29_b.jpg", rating: 4.9, precioCOP: 3700000 },
  { id: 108, nombre: "Múnich", pais: "Alemania", descripcion: "Ciudad de Oktoberfest y arquitectura bávara.", imagen: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/501000/501501-munich.jpg", rating: 4.8, precioCOP: 3600000 },
  { id: 109, nombre: "Colonia", pais: "Alemania", descripcion: "Ciudad sobre el Rin con catedral gótica.", imagen: "https://content.r9cdn.net/rimg/dimg/39/a8/a226c175-city-14508-1640020c415.jpg?crop=true&width=1020&height=498", rating: 4.7, precioCOP: 3500000 },
  { id: 110, nombre: "Hamburgo", pais: "Alemania", descripcion: "Puerto histórico con canales y vida cultural.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Dft2TiaRo_4dP21Ev6_004gXXrb0zIQZLg&s", rating: 4.7, precioCOP: 3500000 },
  { id: 111, nombre: "Viena", pais: "Austria", descripcion: "Capital imperial con música y arquitectura.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzE2iacFuBDI0WdWSGD8-cD77A5n8H9vZYnw&s", rating: 4.9, precioCOP: 3800000 },
  { id: 112, nombre: "Salzburgo", pais: "Austria", descripcion: "Ciudad de Mozart en los Alpes.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/33/f9/7a/salzburg.jpg?w=1200&h=700&s=1", rating: 4.8, precioCOP: 3600000 },
  { id: 113, nombre: "Hallstatt", pais: "Austria", descripcion: "Pueblo alpino picturesco al borde del lago.", imagen: "https://fotografias-2.larazon.es/clipping/cmsimages01/2019/08/09/245E4071-4F4A-486F-A012-D0BC41F99413/98.jpg?crop=2000,1125,x0,y104&width=1900&height=1069&optimize=low&format=webply", rating: 4.9, precioCOP: 3700000 },
  { id: 114, nombre: "Praga", pais: "República Checa", descripcion: "Ciudad de cuento con castillo y puente antiguo.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/36/37/32/caption.jpg?w=1100&h=-1&s=1", rating: 4.9, precioCOP: 2900000 },
  { id: 115, nombre: "Budapest", pais: "Hungría", descripcion: "Ciudad termal con arquitectura grandiosa.", imagen: "https://static.barcelo.com/content/dam/bpt/posts/2023/5/que%20ver%20en%20varsovia%20(1).jpg", rating: 4.9, precioCOP: 2800000 },
  { id: 116, nombre: "Varsovia", pais: "Polonia", descripcion: "Capital histórica reconstruida con patrimonio.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA8xrklzTzy9cATR41fE3L0b_DB7eCvQNQGw&s", rating: 4.7, precioCOP: 2700000 },
  { id: 117, nombre: "Cracovia", pais: "Polonia", descripcion: "Ciudad medieval con plaza y minas de sal.", imagen: "https://cdn.guialowcost.es/wp-content/uploads/panoramica-de-estambul-en-turquia.jpg", rating: 4.8, precioCOP: 2800000 },
  { id: 118, nombre: "Estambul", pais: "Turquía", descripcion: "Ciudad entre Europa y Asia con mezquitas.", imagen: "https://media.tacdn.com/media/attractions-splice-spp-674x446/12/49/5b/42.jpg", rating: 4.9, precioCOP: 3200000 },
  { id: 119, nombre: "Capadocia", pais: "Turquía", descripcion: "Región de formaciones rocosas y globos aerostáticos.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH7nUBKVyItsCOlehRWoBNxwPMvEDJ_0r8BQ&s", rating: 4.9, precioCOP: 3100000 },
  { id: 120, nombre: "Éfeso", pais: "Turquía", descripcion: "Ruinas de ciudad antigua griega.", imagen: "https://www.turismoroma.it/sites/default/files/Roma%20in%20breve.jpg", rating: 4.8, precioCOP: 2900000 },
  { id: 121, nombre: "Roma", pais: "Italia", descripcion: "La ciudad eterna con Coliseo y Vaticano.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9OkK3zF6nJxlWmi5ceeWdLYAPtHPJTR5tng&s", rating: 5.0, precioCOP: 4000000 },
  { id: 122, nombre: "Venecia", pais: "Italia", descripcion: "Ciudad de canales y góndolas sobre el agua.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ2gq47syG5f4SvlU6p1WWXeR49SpjPx0_mA&s", rating: 4.9, precioCOP: 3900000 },
  { id: 123, nombre: "Florencia", pais: "Italia", descripcion: "Cuna del Renacimiento con arte excepcional.", imagen: "https://storage.googleapis.com/mytour-prod/blog/top-7-curiosities-about-milan_2020-10-wp3823865-1-scaled.jpg", rating: 4.9, precioCOP: 3800000 },
  { id: 124, nombre: "Milán", pais: "Italia", descripcion: "Ciudad de moda, arte y arquitectura moderna.", imagen: "https://www.civitatis.com/blog/wp-content/uploads/2024/02/shutterstock_732553141-scaled.jpg", rating: 4.8, precioCOP: 3700000 },
  { id: 125, nombre: "Nápoles", pais: "Italia", descripcion: "Ciudad histórica con pizza y Pompeya cercana.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf5HiRoiCzLZQ-eFQYHktnaRxu795ZAYUK1w&s", rating: 4.7, precioCOP: 3500000 },
  { id: 126, nombre: "Atenas", pais: "Grecia", descripcion: "Cuna de la civilización con la Acrópolis.", imagen: "https://www.capaesculturas.com/wp-content/uploads/7-maravillas-coloso-rodas-antes_f9c8f9d9_1400x788-1-scaled.jpg", rating: 4.8, precioCOP: 3400000 },
  { id: 127, nombre: "Rodas", pais: "Grecia", descripcion: "Isla griega con playas y ruinas antiguas.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDjC0p-boAZRHdixZOv_SHBSIqUxlvWnnIOA&s", rating: 4.8, precioCOP: 3500000 },
  { id: 128, nombre: "Creta", pais: "Grecia", descripcion: "Isla con playas, ruinas minoicas y naturaleza.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUUvY-3DR3JYzTxP6vtZ8Oc2EkB9Ah5_k-pA&s", rating: 4.8, precioCOP: 3600000 },
  { id: 129, nombre: "Mykonos", pais: "Grecia", descripcion: "Isla de playas de lujo y vida nocturna.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/4d/44/26/paros.jpg?w=1400&h=1400&s=1", rating: 4.8, precioCOP: 4200000 },
  { id: 130, nombre: "Paros", pais: "Grecia", descripcion: "Isla con playas tranquilas y pueblos blancos.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDjZLWSLPkAhP-CPBgjRpNNVD2sEBZ0xFvPw&s", rating: 4.7, precioCOP: 3800000 },
  { id: 131, nombre: "Tokio", pais: "Japón", descripcion: "Metrópolis futurista con templos antiguos.", imagen: "https://stories.weroad.es/wp-content/uploads/2023/02/viaje-que-ver-en-kioto.jpg", rating: 4.9, precioCOP: 4500000 },
  { id: 132, nombre: "Kioto", pais: "Japón", descripcion: "Antigua capital con templos y geishas.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrLuUk0Oqrm-oGstC5QJFZW7lwtBYlrd5zaA&s", rating: 4.9, precioCOP: 4400000 },
  { id: 133, nombre: "Osaka", pais: "Japón", descripcion: "Metrópolis de comida y vida nocturna activa.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHMI4ENDFZfGMV-urqQ56_8smzIKne6KAgdg&s", rating: 4.8, precioCOP: 4300000 },
  { id: 134, nombre: "Seúl", pais: "Corea del Sur", descripcion: "Capital moderna con tradición y tecnología.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk8-MWdAUgLG9mRTCPpn0ukLcUK-63mVCXEg&s", rating: 4.8, precioCOP: 4200000 },
  { id: 135, nombre: "Busan", pais: "Corea del Sur", descripcion: "Puerto con playas y templos budistas.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8vBcWD3Lr_ej-mmNFvuuzXfPdJvVduE8teA&s", rating: 4.7, precioCOP: 3900000 },
  { id: 136, nombre: "Bangkok", pais: "Tailandia", descripcion: "Ciudad de templos y vida nocturna intensa.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt946ff9e4985c1319/6731c3a64ef1040e96e55bfc/BCC-2024-EXPLORER-BANGKOK-FUN-THINGS-TO-DO-HEADER_MOBILE.jpg?fit=crop&disable=upscale&auto=webp&quality=60&crop=smart", rating: 4.7, precioCOP: 3200000 },
  { id: 137, nombre: "Phuket", pais: "Tailandia", descripcion: "Isla de playas paradisíacas y resorts.", imagen: "https://i.pinimg.com/736x/bd/e5/bf/bde5bf9ff2616cf48c80864608de4c8d.jpg", rating: 4.8, precioCOP: 3500000 },
  { id: 138, nombre: "Chiang Mai", pais: "Tailandia", descripcion: "Ciudad de templos antiguos y naturaleza.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/03/1c/60/caption.jpg?w=600&h=400&s=1", rating: 4.7, precioCOP: 2800000 },
  { id: 139, nombre: "Bali", pais: "Indonesia", descripcion: "Isla de templos, playas y cultura rica.", imagen: "https://media.iatiseguros.com/wp-content/uploads/2018/05/04005529/bali-que-hacer-Templo-Ulun-Danu.jpg", rating: 4.8, precioCOP: 3400000 },
  { id: 140, nombre: "Singapur", pais: "Singapur", descripcion: "Ciudad-estado futurista multicultural.", imagen: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/542000/542607-singapore.jpg", rating: 4.8, precioCOP: 3800000 },
  { id: 141, nombre: "Hong Kong", pais: "China", descripcion: "Metrópolis con rascacielos y cultura oriental.", imagen: "https://res.klook.com/image/upload/fl_lossy.progressive,q_60/v1755071654/destination/rjgbib6j1mmzviy5gvi1.jpg", rating: 4.9, precioCOP: 4100000 },
  { id: 142, nombre: "Pekín", pais: "China", descripcion: "Capital antigua y moderna con Gran Muralla.", imagen: "https://content.r9cdn.net/rimg/dimg/62/28/22c46ab3-city-3286-164700d5d0b.jpg?width=1366&height=768&xhint=1506&yhint=1211&crop=true", rating: 4.8, precioCOP: 3900000 },
  { id: 143, nombre: "Shanghái", pais: "China", descripcion: "Megalópolis con modernidad y tradición.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt9610c59c9fbe1449/68501f319fd25f2cf6055455/Shanghai_Night-HEADER_MOBILE.jpg?format=webp&quality=60&width=1440", rating: 4.8, precioCOP: 4000000 },
  { id: 144, nombre: "Nueva York", pais: "Estados Unidos", descripcion: "La ciudad que nunca duerme con iconos mundiales.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1cUuNTp1SUCUPxNIUO4nT5ja_BIhcdwY9WQ&s", rating: 4.9, precioCOP: 4500000 },
  { id: 145, nombre: "Los Ángeles", pais: "Estados Unidos", descripcion: "Ciudad de cine, playas y buen clima.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Los_Angeles_with_Mount_Baldy.jpg/330px-Los_Angeles_with_Mount_Baldy.jpg", rating: 4.8, precioCOP: 4200000 },
  { id: 146, nombre: "San Francisco", pais: "Estados Unidos", descripcion: "Ciudad de puente dorado y colinas.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/San_Francisco_Downtown_Aerial%2C_August_2025.jpg/330px-San_Francisco_Downtown_Aerial%2C_August_2025.jpg", rating: 4.9, precioCOP: 4300000 },
  { id: 147, nombre: "Chicago", pais: "Estados Unidos", descripcion: "Ciudad arquitectónica junto al lago Michigan.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA27gNUc2UYLKEABXERCCW4yDzs9raFRpgoA&s", rating: 4.8, precioCOP: 4000000 },
  { id: 148, nombre: "Boston", pais: "Estados Unidos", descripcion: "Ciudad histórica con herencia colonial.", imagen: "https://images.trvl-media.com/place/178239/8970bbdd-3367-4cf8-9ec8-fe9a12776371.jpg?impolicy=resizecrop&rw=450&ra=fit&ch=280", rating: 4.7, precioCOP: 3900000 },
  { id: 149, nombre: "Miami", pais: "Estados Unidos", descripcion: "Ciudad de playas, clima tropical y vida nocturna.", imagen: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/339000/339657-Downtown-Miami.jpg", rating: 4.7, precioCOP: 3800000 },
  { id: 150, nombre: "Washington DC", pais: "Estados Unidos", descripcion: "Capital con monumentos y museos de importancia mundial.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmd61wLHTYDKUhYhHNa5OF6rVe9MbQ_MhmkA&s", rating: 4.8, precioCOP: 3900000 },
  { id: 151, nombre: "Río de Janeiro", pais: "Brasil", descripcion: "Cidade maravillosa con Cristo y playas.", imagen: "https://res.cloudinary.com/worldpackers/image/upload/c_fill,f_auto,h_500,q_auto,w_1024/v1/guides/article_cover/dtceexjjoji0w1ikkp2k?_a=BACADKGT", rating: 4.9, precioCOP: 3600000 },
  { id: 152, nombre: "São Paulo", pais: "Brasil", descripcion: "Megalópolis brasileña con cultura y gastronomía.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Marginal_Pinheiros_e_Jockey_Club.jpg/330px-Marginal_Pinheiros_e_Jockey_Club.jpg", rating: 4.7, precioCOP: 3400000 },
  { id: 153, nombre: "Salvador", pais: "Brasil", descripcion: "Primera capital con playas y cultura afrobrasileña.", imagen: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/dd/dd/02.jpg", rating: 4.7, precioCOP: 3200000 },
  { id: 154, nombre: "Buenos Aires", pais: "Argentina", descripcion: "París de América del Sur con tango y steak.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt76d4ada305c66774/67baef242cce5baadc8f7523/Deensel_Puerto_Madero_Buenos_Aires_(40689219792)_(cropped)_-_Header_Mobile.jpg?format=webp&quality=60&width=1440", rating: 4.9, precioCOP: 3200000 },
  { id: 155, nombre: "Mendoza", pais: "Argentina", descripcion: "Región de vinos bajo cordillera de los Andes.", imagen: "https://d3h1lg3ksw6i6b.cloudfront.net/media/image/2025/08/07/9800890c69ec4266b79e0ad5bc32f655_Mendoza_vista_3_%281%29_%281%29.jpg", rating: 4.8, precioCOP: 2800000 },
  { id: 156, nombre: "Bariloche", pais: "Argentina", descripcion: "Localidad de lagos y montañas en Patagonia.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/d4/93/ff/caption.jpg?w=500&h=400&s=1", rating: 4.8, precioCOP: 2700000 },
  { id: 157, nombre: "Santiago", pais: "Chile", descripcion: "Capital entre Andes y océano Pacífico.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwOckws5BwcZMAPyzwVvnH-FDi2xNs066PZA&s", rating: 4.7, precioCOP: 3200000 },
  { id: 158, nombre: "Atacama", pais: "Chile", descripcion: "Desierto con paisajes lunares únicos.", imagen: "https://www.civitatis.com/blog/wp-content/uploads/2022/12/cordillera-sal-atacama.jpg", rating: 4.8, precioCOP: 2600000 },
  { id: 159, nombre: "Torres del Paine", pais: "Chile", descripcion: "Parque natural de montañas dramáticas en Patagonia.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiJVvVKHziEGxsg8NkT1fTIFMklueQUcJcgg&s", rating: 4.9, precioCOP: 2800000 },
  { id: 160, nombre: "Isla de Pascua", pais: "Chile", descripcion: "Isla remota con famosos moáis.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDM43u3haQ79HSIgHSXbxjpEx2Wleej2ecDQ&s", rating: 4.8, precioCOP: 4500000 },
  { id: 161, nombre: "Lima", pais: "Perú", descripcion: "Capital con gastronomía y patrimonio prehispánico.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2nh7nAPtQXEjFJS2U82bcftx7iz9Bk9fhfg&s", rating: 4.8, precioCOP: 2900000 },
  { id: 162, nombre: "Cusco", pais: "Perú", descripcion: "Antigua capital inca con arquitectura histórica.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Plaza_de_Cusco_Allison_Bellido.jpg/330px-Plaza_de_Cusco_Allison_Bellido.jpg", rating: 4.9, precioCOP: 3100000 },
  { id: 163, nombre: "Valle Sagrado", pais: "Perú", descripcion: "Valle con ruinas incas y pueblos tradicionales.", imagen: "https://image-tc.galaxy.tf/wijpeg-7s1v8e5km8dojs4ckc2dhyi4t/valle-sagrado-destino-unico_wide.jpg?crop=26%2C0%2C1548%2C871", rating: 4.8, precioCOP: 2900000 },
  { id: 164, nombre: "Nazca", pais: "Perú", descripcion: "Famosa por sus líneas geométricas en el desierto.", imagen: "https://travelbuddiesperu.com/wp-content/uploads/2023/03/Lineas-de-Nazca-1400x788.jpg", rating: 4.7, precioCOP: 2700000 },
  { id: 165, nombre: "Quito", pais: "Ecuador", descripcion: "Capital andina con centro histórico en montaña.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ3O40HKEYTPjBvp8SRph9OliJTPCPrqNbaw&s", rating: 4.7, precioCOP: 2600000 },
  { id: 166, nombre: "Islas Galápagos", pais: "Ecuador", descripcion: "Archipiélago único para biodiversidad extrema.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1k9yMVnpAc23kJv-ITTlPSULKTWLURusIJg&s", rating: 4.9, precioCOP: 8000000 },
  { id: 167, nombre: "La Paz", pais: "Bolivia", descripcion: "Capital del mundo más alto con mercados vibrantes.", imagen: "https://content.r9cdn.net/rimg/dimg/59/66/56b9c63c-city-13346-164dcfc0a70.jpg?width=1366&height=768&xhint=3450&yhint=2249&crop=true", rating: 4.6, precioCOP: 2400000 },
  { id: 168, nombre: "Salar de Uyuni", pais: "Bolivia", descripcion: "Desierto de sal más grande del mundo.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGPiou1Af4pk_CoMtdLAvsPzl_1TfHIr8kdw&s", rating: 4.9, precioCOP: 2500000 },
  { id: 169, nombre: "Sucre", pais: "Bolivia", descripcion: "Ciudad blanca con arquitectura colonial conservada.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Sucre%2C_Capital_de_Bolivia.jpg/330px-Sucre%2C_Capital_de_Bolivia.jpg", rating: 4.6, precioCOP: 2200000 },
  { id: 170, nombre: "Cartagena de Indias", pais: "Colombia", descripcion: "Joya colonial amurallada en la costa caribeña.", imagen: "https://www.civitatis.com/f/colombia/cartagena-de-indias/tour-cartagena-completo-589x392.jpg", rating: 4.9, precioCOP: 0 },
  { id: 171, nombre: "Panamá", pais: "Panamá", descripcion: "Ciudad moderna junto al famoso canal.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbsQw1p4YWH8v02j7OuCyKXYzUh_5nTrvucg&s", rating: 4.7, precioCOP: 2800000 },
  { id: 172, nombre: "San José", pais: "Costa Rica", descripcion: "Capital de país verde rodeada de volcanes.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Valencia_Hotel%2C_Santana_Row_%28cropped%29.jpg/250px-Valencia_Hotel%2C_Santana_Row_%28cropped%29.jpg", rating: 4.6, precioCOP: 2400000 },
  { id: 173, nombre: "La Habana", pais: "Cuba", descripcion: "Capital colorida con autos antiguos y história.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdt9D75dSRl53WgLeeSSfMkfX5UPxAeB74jw&s", rating: 4.7, precioCOP: 2600000 },
  { id: 174, nombre: "Punta Cana", pais: "República Dominicana", descripcion: "Resort de playas paradisíacas en el Caribe.", imagen: "https://media.staticontent.com/media/pictures/83239c0a-50e5-44c5-bbb2-bea8292543e4", rating: 4.8, precioCOP: 3600000 },
  { id: 175, nombre: "Puerto Príncipe", pais: "Haití", descripcion: "Capital con historia y cultura caribeña.", imagen: "https://content.r9cdn.net/rimg/dimg/dc/b6/f7f1f15e-city-12630-165e9730119.jpg?width=1366&height=768&xhint=1032&yhint=1038&crop=true", rating: 4.3, precioCOP: 1800000 },
  { id: 176, nombre: "Kingston", pais: "Jamaica", descripcion: "Capital de reggae y cultura caribeña vibrante.", imagen: "https://upload.wikimedia.org/wikipedia/commons/1/10/View_of_Kingston.jpg", rating: 4.6, precioCOP: 2400000 },
  { id: 177, nombre: "Cancún", pais: "México", descripcion: "Resort con playas de arena blanca y ruinas mayas.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwVcRQuo2IPnNoCyx7Gia1PhKtGeWVW33DDg&s", rating: 4.8, precioCOP: 3400000 },
  { id: 178, nombre: "Playa del Carmen", pais: "México", descripcion: "Destino de playas y vida nocturna en el Caribe.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnMbWseYquk_aEQddE31XV9077MF0G3c7Yfw&s", rating: 4.8, precioCOP: 3300000 },
  { id: 179, nombre: "México DF", pais: "México", descripcion: "Capital antigua sobre islotes con museos.", imagen: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_2,w_3840,h_1920,g_auto/dpr_auto/f_auto/q_auto:eco/v1/Mexico-City-GettyImages-638921947?_a=BAVAZGID0", rating: 4.8, precioCOP: 3200000 },
  { id: 180, nombre: "Vancouver", pais: "Canadá", descripcion: "Ciudad costera rodeada de montañas y naturaleza.", imagen: "https://travel.destinationcanada.com/_next/image?url=https%3A%2F%2Fadmin.destinationcanada.com%2Fsites%2Fdefault%2Ffiles%2Fimages%2Farticle%2Fstanley_park.jpg&w=1920&q=75", rating: 4.8, precioCOP: 3900000 },
  { id: 181, nombre: "Toronto", pais: "Canadá", descripcion: "Ciudad multicultural con Cataratas del Niágara.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt96514b1f58ed985c/67f6b11823ddbec0855132c6/iStock-1903061976-2-Header_Mobile.jpg?format=webp&quality=60&width=1440", rating: 4.8, precioCOP: 4000000 },
  { id: 182, nombre: "Montreal", pais: "Canadá", descripcion: "Ciudad francesa con vida cultural intensa.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/f2/6b/caption.jpg?w=600&h=500&s=1", rating: 4.8, precioCOP: 3900000 },
  { id: 183, nombre: "Sydney", pais: "Australia", descripcion: "Metrópolis costera con ópera famosa.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/cf/69/07/sydney-harbour.jpg?w=900&h=500&s=1", rating: 4.9, precioCOP: 4800000 },
  { id: 184, nombre: "Melbourne", pais: "Australia", descripcion: "Ciudad cultural de arte callejero y café.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/ba/8d/5f/caption.jpg?w=1200&h=700&s=1&cx=4163&cy=2590&chk=v1_a0ed89eeb3b0881fb970", rating: 4.8, precioCOP: 4700000 },
  { id: 185, nombre: "Brisbane", pais: "Australia", descripcion: "Ciudad cálida con playas y vida exterior.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/4d/45/4e/brisbane.jpg?w=1200&h=700&s=1", rating: 4.7, precioCOP: 4500000 },
  { id: 186, nombre: "Auckland", pais: "Nueva Zelanda", descripcion: "Ciudad con dos puertos naturales y volcanes.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Auckland_skyline_-_May_2024_%282%29.jpg/330px-Auckland_skyline_-_May_2024_%282%29.jpg", rating: 4.8, precioCOP: 4900000 },
  { id: 187, nombre: "Wellington", pais: "Nueva Zelanda", descripcion: "Capital compacta entre montañas y mar.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/09/e7/2e/the-cable-car.jpg?w=1200&h=700&s=1", rating: 4.7, precioCOP: 4700000 },
  { id: 188, nombre: "Dubái", pais: "Emiratos Árabes Unidos", descripcion: "Metrópolis del lujo y rascacielos ultramodernos.", imagen: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/ef/4c/9c.jpg", rating: 4.8, precioCOP: 5200000 },
  { id: 189, nombre: "Abu Dabi", pais: "Emiratos Árabes Unidos", descripcion: "Capital rica con mezquitas y arquitectura.", imagen: "https://content.r9cdn.net/rimg/dimg/a8/85/bbf8aa0b-city-9457-164d6a9147e.jpg?width=1200&height=630&xhint=2731&yhint=1539&crop=true", rating: 4.7, precioCOP: 5000000 },
  { id: 190, nombre: "Doha", pais: "Qatar", descripcion: "Capital moderna con rascacielos futuristas.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/c9/8f/b0/view-from-corniche.jpg?w=1200&h=-1&s=1", rating: 4.7, precioCOP: 5100000 },
  { id: 191, nombre: "Marrakech", pais: "Marruecos", descripcion: "Ciudad roja con medinas y palacios tradición.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMa9blvqXeEQPQcmzdfJKx3Dj8001pbDE2hw&s", rating: 4.8, precioCOP: 2800000 },
  { id: 192, nombre: "Fez", pais: "Marruecos", descripcion: "Ciudad antigua con medina laberíntica medieval.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdejOfSv1uur2ocID6abeV6CRQNjfwGRvFEQ&s", rating: 4.7, precioCOP: 2600000 },
  { id: 193, nombre: "Casablanca", pais: "Marruecos", descripcion: "Puerto moderno con mezquita blanca famosa.", imagen: "https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blta01aa4bb8f286df8/68683c9f242610b914b2c95a/iStock-2152434554-MOBILE_HEADER.jpg?fit=crop&disable=upscale&auto=webp&quality=60&crop=smart", rating: 4.7, precioCOP: 2700000 },
  { id: 194, nombre: "Jartum", pais: "Sudán", descripcion: "Capital en confluencia del Nilo.", imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Elmek_Nimir_Bridge.jpg/330px-Elmek_Nimir_Bridge.jpg", rating: 4.4, precioCOP: 1900000 },
  { id: 195, nombre: "El Cairo", pais: "Egipto", descripcion: "Capital antigua con grandes pirámides cercanas.", imagen: "https://www.civitatis.com/blog/wp-content/uploads/2025/01/que-ver-cairo-egipto.jpg", rating: 4.7, precioCOP: 3200000 },
  { id: 196, nombre: "Alejandría", pais: "Egipto", descripcion: "Puerto histórico en el Mediterráneo.", imagen: "https://www.civitatis.com/f/egipto/egipto/guia/alejandria-m.jpg", rating: 4.6, precioCOP: 3000000 },
  { id: 197, nombre: "Copenhague", pais: "Dinamarca", descripcion: "Capital nórdica con Tívoli y canales.", imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6oaxIadxL7HtnFMfSGsE0d9tKWT8F8_w2_A&s", rating: 4.8, precioCOP: 4000000 },
  { id: 198, nombre: "Estocolmo", pais: "Suecia", descripcion: "Capital sobre islas con Palacio Real.", imagen: "https://www.civitatis.com/blog/wp-content/uploads/2019/12/que-ver-estocolmo.jpg", rating: 4.8, precioCOP: 4100000 },
  { id: 199, nombre: "Oslo", pais: "Noruega", descripcion: "Capital escandinava con fiordo y naturaleza.", imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/ce/24/d3/20170704-185513-largejpg.jpg?w=1200&h=-1&s=1", rating: 4.8, precioCOP: 4200000 },
  { id: 200, nombre: "Reikiavik", pais: "Islandia", descripcion: "Capital mundial de auroras y geiseres.", imagen: "https://gti.images.tshiftcdn.com/2978646/x/0/las-12-mejores-cosas-que-hacer-en-reikiavik-12.jpg?ixlib=php-3.3.0&w=883", rating: 4.9, precioCOP: 5300000 }
];